subgraphs:
  people:
    routing_url: http://localhost:4001/graphql
    schema:
      subgraph_url: http://localhost:4001/graphql
  films:
    routing_url: http://localhost:4002/graphql
    schema:
      subgraph_url: http://localhost:4002/graphql
# subgraphs:
#   products:
#     routing_url: https://rover.apollo.dev/quickstart/products/graphql
#     schema:
#       subgraph_url: https://rover.apollo.dev/quickstart/products/graphql
#   reviews:
#     routing_url: https://rover.apollo.dev/quickstart/reviews/graphql
#     schema:
#       subgraph_url: https://rover.apollo.dev/quickstart/reviews/graphql